
  // This file was generated by Prisma and assumes you have installed the following:
  // npm install --save-dev prisma dotenv
  import "dotenv/config";
  import { defineConfig, env } from "prisma/config";

  // export default defineConfig({
  //   earlyAccess: true,
  //   schema:"./prisma/schema.prisma",
  //   migrate:{
  //     connectionString: env("DATABASE_URL"),

  //   },

  // });
  export default defineConfig({

    schema: "prisma/schema.prisma",
    migrations: {
      path: "prisma/migrations",
    },
    engine: "classic",
    datasource: {
      url: env("DATABASE_URL"),
    },
  });
